### PR TITLE
Display the stars as per mapping level beside the username

### LINKED ISSUE #7053: [BUG] Missing star indicator next to the user name and unable to filter users by status
**Describe the bug**
Status of the mapper is not presented by the half-filled star (intermediate level) or full-filled star (advanced mapper) and users cannot be filtered by status.

**To Reproduce**
1. Go to any project contributions tab. For example https://tasks.hotosm.org/projects/14355/contributions
2. Star icon is not presented next to the mapper username despite the advanced level reached
2.1. For example user anthaas (see the profile https://tasks.hotosm.org/users/anthaas)

**Expected behavior**
1. To be able to see the star icon indicator
2. To be able to filter by status

**Screenshots**
Missing star indicator:
Image

Image

Broken filter
Image

**Desktop (please complete the following information):**
 - OS: macOS 26.0.1
 - Browser Vivaldi 7.6.3797.63

### PR DESCRIPTION
**Pull request by suzit-10**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation
- [x] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue

- Fixes #7053 

## Describe this PR
Display  stars beside the username on the contributors list as follows:

- The first three default levels represent:
> - 1.    Beginner → empty star (black)
> - 2.    Intermediate → half-filled star (black)
> - 3.    Advanced → filled star (black)

- A yellow-filled star represents the new Super Mapper level.

For dynamic support, the `blue star` is introduced, which represents the level above the threes first levels (Beginner, Intermediate, and Advanced), below the highest level (super mapper).

### CODE REVIEW

File: frontend/src/components/svgIcons/index.js [hunk 1]
```diff
@@ -23,7 +23,13 @@ export { ExitIcon } from './exit';
 export { EyeIcon } from './eye';
 export { HomeIcon } from './home';
 export { LockIcon } from './lock';
-export { StarIcon, FullStarIcon, HalfStarIcon } from './star';
+export {
+  StarIcon,
+  FullStarIcon,
+  HalfStarIcon,
+  FullStartIconYellow,
+  FullStartIconBlue,
```
Comment (ramyaragupathy) [inline frontend/src/components/svgIcons/index.js]: FullStar

File: frontend/src/components/svgIcons/star.js [hunk 2]
```diff
@@ -40,3 +40,28 @@ export class HalfStarIcon extends PureComponent {
     );
   }
 }
+
+export class FullStartIconYellow extends PureComponent {
```
Comment (ramyaragupathy) [inline frontend/src/components/svgIcons/star.js]: FullStar

File: frontend/src/components/taskSelection/contributions.js [hunk 3]
```diff
@@ -12,46 +12,65 @@ import {
...
+      return <StarIcon className="h1 w1 v-mid pb1" />;
+    } else if (currentIndex === 1) {
+      // Half star for second position
+      return <HalfStarIcon className="h1 w1 v-mid pb1" />;
+    } else if (currentIndex === 2) {
+      // Full star for third position
+      return <FullStarIcon className="h1 w1 v-mid pb1" />;
+    } else if (currentIndex === lastIndex) {
+      // Yellow star for last position (highest level)
+      return <FullStartIconYellow className="h1 w1 v-mid pb1" />;
```
Comment (ramyaragupathy) [inline frontend/src/components/taskSelection/contributions.js]: Star

File: frontend/src/components/taskSelection/contributions.js [hunk 4]
```diff
@@ -12,46 +12,65 @@ import {
...
+    } else {
+      // Full stars for anything in between
+      return <FullStartIconBlue className="h1 w1 v-mid pb1" />;
```
Comment (ramyaragupathy) [inline frontend/src/components/taskSelection/contributions.js]: Star

**Review by ramyaragupathy — COMMENTED** [review]
Highlighted a few name updates to stay consistent with the rest of the names and context.
