### PR TITLE
Use FallbackComponent when route throws an exception while rendering

### LINKED ISSUE #5754: Display our custom FallbackComponent when exceptions are thrown
This would be a weird-looking error for the user.

235650082-499de215-1b5b-46fe-bf28-31f0cf0dc390

Instead, display our custom fallback component that offers the Contact Us and Return buttons.

### PR DESCRIPTION
**Pull request by HelNershingThapa**
Resolves #5754

### CODE REVIEW

File: frontend/src/App.js [hunk 1]
```diff
@@ -33,11 +33,10 @@ const App = () => {
...
         <div className="w-100 base-font bg-white" lang={locale}>
           <main className="cf w-100 base-font">
-            <Suspense
-              fallback={<ReactPlaceholder showLoadingAnimation={true} rows={30} delay={300} />}
-            >
-              <RouterProvider router={router} />
+            <Suspense fallback={<ReactPlaceholder showLoadingAnimation rows={30} delay={300} />}>
+              <RouterProvider router={router} fallbackElement={<Preloader />} />
             </Suspense>
+            <RouterProvider router={router} fallbackElement={<Preloader />} />
```
Comment (Aadesh-Baral) [inline frontend/src/App.js:39]: It looks like there are two instances of the <RouterProvider> component being rendered vertically, which is causing the app to appear twice on the page. This must have been an oversight, and we should remove one of the instances to fix the issue.

**Review by Aadesh-Baral — CHANGES_REQUESTED** [review]

**Review by Aadesh-Baral — APPROVED** [review]

File: frontend/src/App.js (hunk 1 above)
Comment (HelNershingThapa) [reply frontend/src/App.js]: imagine shipping that haha. thanks for the catch @Aadesh-Baral. appreciate it
